services:
  app:
    build: .
    volumes:
      - /usr/bin/infisical:/usr/bin/infisical:ro
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
      - INFISICAL_PROJECT_ID=${INFISICAL_PROJECT_ID}
      - INFISICAL_ENVIRONMENT=${INFISICAL_ENVIRONMENT}
      - INFISICAL_API_URL=${INFISICAL_API_URL}
      - INFISICAL_DISABLE_LOGGING=${INFISICAL_DISABLE_LOGGING}
      - INFISICAL_LOG_LEVEL=${INFISICAL_LOG_LEVEL}
    # Mana bu yerda ENTRYPOINT ni composega ko'chirdik
    command: >
      sh -c "cd /app && infisical run -- sh entrypoint.sh"
