[phases.setup]
nixPkgs = ["php82", "nodejs_22"]

[phases.install]
cmds = [
  "npm install",
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php-fpm"
