[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "curl", "php82Extensions.pdo_pgsql"]

[phases.install]
cmds = [
  "curl -Ls https://cli.doppler.com/install.sh | sh",
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache"
]

[start]
PHP-FPM ni doppler bilan ishga tushiramiz
# cmd = "doppler run -- php-fpm -F"
