[phases.setup]
nixPkgs = ["php82", "nodejs_22", "php82Packages.composer", "curl"]

[phases.install]
cmds = [
  # Doppler CLI install
  "curl -Ls https://cli.doppler.com/install.sh | sh",

  # PHP deps
  "composer install --no-dev --optimize-autoloader",

  # Node deps
  "npm install"
]

[phases.build]
cmds = [
  "npm run build",

  # Laravel optimize
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "doppler run -- php-fpm"
