name: deploy
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy-to-host:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        
      - name: Sync to web root
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            ./* "D:/laragon/www/"
        shell: bash

      - name: Composer Install
        run: composer install --no-dev --optimize-autoloader
        working-directory: D:/laragon/www/onlyOffice


