name: deploy
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy-to-host:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Move repo to Laragon
        run: robocopy "C:\actions-runner\_work\onlyOffice\onlyOffice" "D:\laragon\www\onlyOffice" /MIR /COPYALL /R:3 /W:1
        shell: cmd
        
      - name: Composer Install
        run: |
          composer install --no-dev --optimize-autoloader
        shell: cmd
        working-directory: 'D:/laragon/www/onlyOffice'


